# Generated by Django 4.2.11 on 2024-04-09 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('family', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bad_associations', models.ManyToManyField(related_name='bad_associations', to='permasite.vegetable')),
                ('good_associations', models.ManyToManyField(related_name='good_associations', to='permasite.vegetable')),
                ('ref_vegetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permasite.vegetable')),
            ],
        ),
    ]
