# Generated by Django 4.2.11 on 2024-04-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permasite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='family',
            field=models.CharField(max_length=200),
        ),
    ]
