# Generated by Django 4.2.11 on 2024-08-09 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permasite', '0003_goodassociation_delete_association'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodassociation',
            name='left_vegetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_left_associations', to='permasite.vegetable'),
        ),
        migrations.AlterField(
            model_name='goodassociation',
            name='right_vegetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_right_associations', to='permasite.vegetable'),
        ),
        migrations.CreateModel(
            name='BadAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('left_vegetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bad_left_associations', to='permasite.vegetable')),
                ('right_vegetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bad_right_associations', to='permasite.vegetable')),
            ],
        ),
    ]
